### ISSUE TITLE
Undefined variable grub_cfg & grub2-mkconfig doesn't exist

### ISSUE THREAD

**Issue by ricardobranco777** [florianutz/Ubuntu1604-CIS#13]
I get this error:

> RUNNING HANDLER [Ubuntu1604-CIS : generate new grub config] **************************************************************************************************
> fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'grub_cfg' is undefined\n\nThe error appears to have been in '/root/smtt/ansible/Ubuntu1604-CIS/handlers/main.yml': line 29, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: generate new grub config\n  ^ here\n"}

Also, the command `grub2-mkconfig` should be renamed to `grub-mkconfig`:

> $ grub2-mkconfig
> No command 'grub2-mkconfig' found, did you mean:
>  Command 'grub-mkconfig' from package 'grub-common' (main)
> grub2-mkconfig: command not found

**Comment by florianutz** [comment]
Fixed by #17
