### ISSUE TITLE
Requirement.yml is missing 

### ISSUE THREAD

**Issue by sangeeta667143** [florianutz/Ubuntu1604-CIS#22]
HI Florian , 
1. ansible-galaxy install -p roles -r requirements.yml in this command requirement.yml is missing .

2. ERROR! 'register' is not a valid attribute for a Play

The error appears to have been in '/etc/ansible/Sango/Ubuntu1604-CIS/tasks/prelim.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

---
The offending line appears to be:

---
- name: PRELIM | List users accounts
  ^ here

I am geeting this issue , can you please help me here .

**Comment by florianutz** [comment]
Hi,

regarding 1: Please take a look please take a look at `README.md`. There you can find example content for the `requirements.yml`

regarding 2: Unfortunately, I can not understand what you are doing. Can you please cleanup all files from the role and try to reinstall with the ansible-galaxy command.
