### ISSUE TITLE
NTP configuration fails (chronyd)

### ISSUE THREAD

**Issue by AlexanderBB** [florianutz/Ubuntu1604-CIS#26]
This list syntax produce wrong output to the chrony.conf file (possible other files, that are using FOR loop). To be more precise it loops through the addresses as each letter is a separate string and this results a new row for each of them.
E.g.
server 0 minpoll 8
server . minpoll 8
server p minpoll 8
server o minpoll 8
...
etc.
This seems to occur after this [commit](https://github.com/florianutz/Ubuntu1604-CIS/commit/c499cfe0005cad7b2f515807d5216d8feada6860).

**Comment by florianutz** [comment]
I updated the configuration in `dev` branch. Can you please validate that configuration in your environment.

**Comment by AlexanderBB** [comment]
The configuration is looking good, thank you! Also your work is much appreciated.
