### ISSUE TITLE
it looks like this line is out of order

### ISSUE THREAD

**Issue by J-Robinson042519** [florianutz/Ubuntu1604-CIS#31]
https://github.com/florianutz/Ubuntu1604-CIS/blob/8b12f248491aabc60c6c69ddedbfcfa6a7ae6edf/defaults/main.yml#L165

**Comment by florianutz** [comment]
@J-Robinson042519 yes it is.
The default values are in the same order than the tasks itself.
This task must run before the other 4.2.x tasks because there are dependencies.
