### ISSUE TITLE
Use version tags in Galaxy

### ISSUE THREAD

**Issue by smiller171** [florianutz/Ubuntu1604-CIS#32]
Currently you have version tags in GitHub, but those versions are not reflected in Ansible Galaxy. It would be very helpful for me if you would set up Galaxy to use those version tags.

**Comment by florianutz** [comment]
You are right. It looks like Galaxy only accept semantic versioning. I thought the others also worked some time ago. But it doesn't matter. Thanks for your note. I fixed it and will use tags more often.
